### ISSUE TITLE
Second Jaccard value

### ISSUE THREAD

**Issue by EHRC** [dassencio/blog#10]
**Post URL**

https://dassencio.org/102

**Description**

The second case should be $\left(\frac{r_2}{r_1}\right)^2$.
Also thanks for the good explanation.
Have a nice day

**Comment by dassencio** [comment]
Hi @EHRC 👋🙂. Are you referring to case 2 in the summary? Thanks!

![Image](https://github.com/user-attachments/assets/827931dd-1f3f-4b05-a17c-fd2ce814237a)

**Comment by EHRC** [comment]
Yes, but I missed the part where you said that it's the intersection area.
So, my bad. I was speaking of the Jaccard value $\displaystyle \frac{A\cap B}{A\cup B}$.
Again, thanks for your material.

**Comment by dassencio** [comment]
Understood. Thanks for clarifying 👍
